require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
