require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 130

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/NamedSubject:
  Enabled: false
